language: scala
scala:
- 2.12.3
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: lA90WFRbT6Xl5wO5UhZrsCHYf1ynK5g1VIRGnHHI/I4ZBvnY3Ge+PGe8jDjikPyUO40KLnpy6A5Lc71TdZ+Uj/o9cKWfQmM4hwylYipD5j3D+dbYwM5LkKt1b/1P4J0+C1FLsg5vqVPhqHO30RWOs9VnSQ0jYaRrszKCFS8kof5YBFnUkeJfF4UhFQ0Fxt7m9DihwRs3Fy0ATq27z0c50v25eUFEMLn77+tAYEYg9YwNxCtXDrsHzCiozDtNCZ07deb/Totw4PPjvVy3exUS3Dto/lcRal8R6YMhfPKb9Q5cEnIiFjHObX+U8yXzm86WbQje0gLO3LCoHz6lxIPcrSRF3qKqIbEktzMGObPL4QnRVRXghUsVcpfvnbYyYuClCImruyNKmoCjy2cRAoKEBZWE+w8YS412GKnYIvqhuVvhGZe2RC6kkmryu5EnjMbu+H5bsavL9PU3yv2nzHcWGLPlEMLbW067XNj0YGvJ/HaEqom4F8YdLebiMw8oXmtRw6ELb4y5jbofUk/YyXEqzgTgr+dfK7xuPusvu2vrjgBO9zTyQgoi2edIoVomQPlqNohS72l3W8hL2vOPERgXmcfaMQxFSE1V3BxB7EwtCmu0tHKi0h7JGN4dqQ0Id+ckw1XNxEH+sO3vtetiWvEPmyttVs5Hh+D75D9C9SCdb2M=
